import type { Locale } from "../i18n";

const zh = {
  cancel: "取消",
  close: "关闭",
  later: "稍后处理",
  preview: "查看差异",
  discard: "丢弃",
  currentFile: "当前文件",
  unsavedEdits: "未保存内容",
  localDraft: "本机草稿",
  draft: "草稿",
  previousSave: "上次保存版本",
  savedBefore: "保存前",
  unknownTime: "未知时间",
  emptyDocument: "（空文档）",
  closeTitle: "退出 Moyang Reader？",
  closeDescription: "当前文档有未保存修改。请选择如何退出。",
  closeFile: "当前文件",
  closeEdits: "当前编辑未写回原文件",
  closeDraft: "已保留可恢复的草稿副本",
  closeExitNote: "直接退出不会写回原文件；草稿副本仍可恢复。",
  closeSaveNote: "保存并退出会先保存当前修改；保存失败时不会退出。",
  closeExit: "退出 Moyang Reader",
  closeSave: "保存并退出",
  overwriteTitle: "覆盖外部修改？",
  overwriteDescription: "原文件已被其他程序修改。确认后，当前编辑将覆盖磁盘上的版本。",
  overwriteDisk: "磁盘版本已在外部改变",
  overwriteEdits: "当前编辑仍在窗口中",
  overwriteNote: "不确定时请取消，然后重新载入或另存为。",
  overwriteConfirm: "确认覆盖保存",
  discardTitle: "丢弃草稿？",
  discardDescription: "确定丢弃“{name}”的本机草稿吗？",
  discardNote: "此操作无法撤销；原文件不会被修改。",
  discardConfirm: "丢弃草稿",
  clearTitle: "清空全部草稿？",
  clearDescription: "确定清空全部未保存草稿吗？",
  clearNote: "此操作无法撤销；原文件不会被修改。",
  clearConfirm: "清空全部草稿",
  historyTitle: "清理阅读记录？",
  historyDescription: "这会删除本机累计阅读时长。",
  historyNote: "原文档、最近打开、阅读位置和草稿不受影响；此操作无法撤销。",
  historyConfirm: "清理阅读记录",
  externalModified: "{name} 已被其他程序修改。当前编辑仍在窗口中，不会自动覆盖原文件。",
  externalDeleted: "{name} 已被删除或移走。当前编辑仍在窗口中，不会自动写回原路径。",
  externalReload: "重新载入",
  externalOverwrite: "覆盖保存",
  externalSaveAs: "另存为",
  noticeDraft: "{name} 有上次未保存的本机草稿（{time}）。",
  noticeDraftSource: "当前打开的是文件版本；草稿是本机副本。先查看差异，再决定是否恢复。",
  noticeDiff: "相比当前版本：新增 {added} 行、移除 {removed} 行、{hunks} 个变更区域，字符 {delta}。",
  noticeSame: "草稿与当前版本内容相同，不需要恢复。",
  noticePreviewAria: "查看当前文件与草稿的差异并决定是否恢复",
  previousNotice: "{name} 保留了上一保存版本",
  previousSource: "这是保存前的本机备份，不会自动覆盖当前文件。先查看差异，再决定是否恢复到编辑区。",
  previousDiff: "上一保存版本：新增 {added} 行、移除 {removed} 行、{hunks} 个变更区域，字符 {delta}。",
  previousSame: "上一保存版本与当前版本内容相同，不需要恢复。",
  previousPreviewAria: "查看当前文件与上一保存版本的差异并决定是否恢复",
  ignore: "忽略",
  centerTitle: "未保存草稿",
  centerCloseAria: "关闭草稿恢复中心",
  centerOpenAria: "打开 {name} 的当前文件（不会自动恢复草稿）",
  centerPreviewAria: "查看 {name} 当前文件与草稿的差异",
  centerDiscardAria: "丢弃 {name} 草稿",
  centerCurrent: "当前文件 · 不会自动恢复草稿",
  centerDiff: "已打开内容差异：+{added} 行 / −{removed} 行 · {hunks} 个区域 · 字符 {delta}{qualifier}",
  centerQuick: " · 快速摘要",
  centerSame: "已打开内容与草稿相同 · 无需恢复",
  centerPending: "查看差异时将读取当前文件 · 不会自动恢复",
  centerFooter: "先比较当前文件与草稿；恢复只进入编辑区，点击“保存”后才写回文件。",
  centerClear: "清空全部",
  comparisonTitle: "恢复前查看差异",
  comparisonCloseAria: "关闭{name}差异",
  comparisonCurrent: "当前版本",
  comparisonBase: "比较基线",
  comparisonCurrentDisk: "当前磁盘版本",
  comparisonCurrentPreview: "当前打开版本（浏览器预览）",
  comparisonSavedPreview: "草稿保存时的原文（浏览器预览）",
  comparisonIntro:
    "当前版本是此刻可读取的文件内容，{candidate}是{description}。当前比较基线：{baseline}。恢复只替换编辑区，点击“保存”后才写回原文件。",
  comparisonDraftDescription: "保存在本机的未保存快照",
  comparisonDetailsAria: "差异详情",
  comparisonPreviousDescription: "保存前保留的本机版本",
  comparisonDraftDetail: "本机恢复快照 · {time}",
  comparisonPreviousDetail: "文件保存前的本机备份",
  comparisonSourcesAria: "当前版本与{name}来源",
  comparisonLegendAria: "差异符号说明",
  comparisonRemoved: "当前版本有、{name}中移除",
  comparisonAdded: "{name}新增",
  comparisonStatsAria: "{name}变更摘要",
  comparisonPreviewAria: "{name}差异预览",
  comparisonCurrentLines: "当前版本行",
  comparisonBaselineLines: "比较基线行",
  comparisonCandidateLines: "{name}行",
  comparisonAddedLines: "新增行",
  comparisonRemovedLines: "移除行",
  comparisonCharacters: "字符变化",
  comparisonHunks: "变更区域",
  comparisonBackupSource: "备份来源",
  comparisonDraftSaved: "草稿保存",
  comparisonLoadingTitle: "正在读取当前版本",
  comparisonLoadingDescription: "正在读取此刻的磁盘文件；读取完成前不会允许恢复。",
  comparisonUnavailableTitle: "无法判断是否需要恢复",
  comparisonUnavailableDescription: "当前文件无法读取，暂时不能可靠比较，也不会直接恢复{name}。",
  comparisonNeedsCurrentTitle: "还需要核对当前文件",
  comparisonNeedsCurrentDescription: "这里只能与{name}保存时的原文比较；打开当前文件后再决定是否恢复。",
  comparisonSameTitle: "无需恢复",
  comparisonSameDescription: "{name}与当前版本内容相同，不需要恢复。",
  comparisonChangedTitle: "建议先核对",
  comparisonChangedDescription: "草稿保存后原文件又发生了变化；请确认两边内容后，再恢复到编辑区。",
  comparisonReadyDraftTitle: "存在未保存内容",
  comparisonReadyPreviousTitle: "可以回到上一保存版本",
  comparisonReadyDraftDescription: "如果这些内容需要保留，可以恢复到编辑区；点击“保存”后才会写回原文件。",
  comparisonReadyPreviousDescription: "如果需要回到上一版，可以恢复到编辑区；点击“保存”后才会写回原文件。",
  comparisonReading: "正在读取当前磁盘版本…",
  comparisonReadError: "无法判断当前差异",
  comparisonReadFallback: "当前文件不可访问，请确认文件仍存在且有读取权限。",
  comparisonRetry: "重新读取当前版本",
  comparisonModifiedWarning: "当前编辑区还有未保存修改；恢复会替换这些修改，但不会自动覆盖磁盘文件。",
  comparisonChangedWarning: "原文件在草稿保存后又发生过变化，以上差异已按当前磁盘版本计算。",
  comparisonOldBaseWarning:
    "当前文件尚未在这里读取；以上内容只与{name}保存时的原文比较，不能代表此刻磁盘文件的完整差异。",
  comparisonNoDiff: "当前版本与{name}没有可见差异，不需要恢复。",
  comparisonTruncated: "文档较长，仅显示差异附近的有限内容。",
  comparisonApproximate: "文档较长，已使用快速差异摘要；恢复前建议打开编辑区再次确认全文。",
  comparisonLoadingAction: "正在读取…",
  comparisonUnavailableAction: "暂不可恢复",
  comparisonRestoreAction: "恢复到编辑区",
  comparisonOpenAction: "打开文档继续确认",
} as const;

type SafetyCopyKey = keyof typeof zh;

const en: Record<SafetyCopyKey, string> = {
  cancel: "Cancel",
  close: "Close",
  later: "Later",
  preview: "Review differences",
  discard: "Discard",
  currentFile: "Current file",
  unsavedEdits: "Unsaved edits",
  localDraft: "Local draft",
  draft: "Draft",
  previousSave: "Previous saved version",
  savedBefore: "Before save",
  unknownTime: "Unknown time",
  emptyDocument: "(Empty document)",
  closeTitle: "Quit Moyang Reader?",
  closeDescription: "The current document has unsaved edits. Choose how to quit.",
  closeFile: "Current file",
  closeEdits: "The edits have not been written to the file",
  closeDraft: "A recoverable draft copy has been kept",
  closeExitNote: "Quitting now will not change the file; the draft copy remains recoverable.",
  closeSaveNote: "Save and quit will save the edits first; a failed save will not close the app.",
  closeExit: "Quit Moyang Reader",
  closeSave: "Save and quit",
  overwriteTitle: "Overwrite external changes?",
  overwriteDescription:
    "Another program changed the file. Confirming will replace the version on disk with your edits.",
  overwriteDisk: "The disk version changed externally",
  overwriteEdits: "Your edits are still in this window",
  overwriteNote: "If unsure, cancel and choose Reload or Save as instead.",
  overwriteConfirm: "Overwrite and save",
  discardTitle: "Discard draft?",
  discardDescription: "Discard the local draft for “{name}”?",
  discardNote: "This cannot be undone. The original file will not change.",
  discardConfirm: "Discard draft",
  clearTitle: "Clear all drafts?",
  clearDescription: "Clear all unsaved local drafts?",
  clearNote: "This cannot be undone. The original files will not change.",
  clearConfirm: "Clear all drafts",
  historyTitle: "Clear reading history?",
  historyDescription: "This deletes reading time recorded on this device.",
  historyNote: "Documents, recent files, reading positions, and drafts remain. This cannot be undone.",
  historyConfirm: "Clear reading history",
  externalModified:
    "Another program changed {name}. Your edits remain in this window and will not overwrite the file automatically.",
  externalDeleted:
    "{name} was deleted or moved. Your edits remain in this window and will not be written to the old path automatically.",
  externalReload: "Reload",
  externalOverwrite: "Overwrite and save",
  externalSaveAs: "Save as",
  noticeDraft: "{name} has a locally saved unsaved draft ({time}).",
  noticeDraftSource: "The open version is the file; the draft is a local copy. Review differences before restoring.",
  noticeDiff:
    "Compared with the current version: {added} added lines, {removed} removed lines, {hunks} changed areas, {delta} characters.",
  noticeSame: "The draft matches the current version. No recovery is needed.",
  noticePreviewAria: "Review the differences between the current file and draft before restoring",
  previousNotice: "A previous saved version of {name} is available",
  previousSource:
    "This local backup was made before saving and will not overwrite the current file automatically. Review differences before restoring it to the editor.",
  previousDiff:
    "Previous saved version: {added} added lines, {removed} removed lines, {hunks} changed areas, {delta} characters.",
  previousSame: "The previous saved version matches the current file. No recovery is needed.",
  previousPreviewAria: "Review the differences between the current file and previous saved version before restoring",
  ignore: "Ignore",
  centerTitle: "Unsaved drafts",
  centerCloseAria: "Close draft recovery center",
  centerOpenAria: "Open the current file for {name} without restoring its draft",
  centerPreviewAria: "Review the differences between the current file and draft for {name}",
  centerDiscardAria: "Discard the draft for {name}",
  centerCurrent: "Current file · draft not restored automatically",
  centerDiff: "Open content difference: +{added} / −{removed} lines · {hunks} areas · {delta} characters{qualifier}",
  centerQuick: " · quick summary",
  centerSame: "Open content matches draft · no recovery needed",
  centerPending: "Review will read the current file · no automatic recovery",
  centerFooter: "Compare the current file and draft first. Recovery only changes the editor; Save writes to the file.",
  centerClear: "Clear all",
  comparisonTitle: "Review differences before recovery",
  comparisonCloseAria: "Close differences for {name}",
  comparisonCurrent: "Current version",
  comparisonBase: "Comparison baseline",
  comparisonCurrentDisk: "Current file on disk",
  comparisonCurrentPreview: "Current open version (browser preview)",
  comparisonSavedPreview: "Original file when draft was saved (browser preview)",
  comparisonIntro:
    "The current version is the readable file now; {candidate} is {description}. Comparison baseline: {baseline}. Recovery only changes the editor; Save writes to the file.",
  comparisonDraftDescription: "an unsaved snapshot stored on this device",
  comparisonDetailsAria: "Difference details",
  comparisonPreviousDescription: "a local version kept before saving",
  comparisonDraftDetail: "Local recovery snapshot · {time}",
  comparisonPreviousDetail: "Local backup made before saving",
  comparisonSourcesAria: "Sources for the current version and {name}",
  comparisonLegendAria: "Difference symbols",
  comparisonRemoved: "In current version, removed from {name}",
  comparisonAdded: "Added in {name}",
  comparisonStatsAria: "Change summary for {name}",
  comparisonPreviewAria: "Difference preview for {name}",
  comparisonCurrentLines: "Current version lines",
  comparisonBaselineLines: "Baseline lines",
  comparisonCandidateLines: "{name} lines",
  comparisonAddedLines: "Added lines",
  comparisonRemovedLines: "Removed lines",
  comparisonCharacters: "Character change",
  comparisonHunks: "Changed areas",
  comparisonBackupSource: "Backup source",
  comparisonDraftSaved: "Draft saved",
  comparisonLoadingTitle: "Reading the current version",
  comparisonLoadingDescription: "Reading the file on disk now; recovery stays unavailable until this completes.",
  comparisonUnavailableTitle: "Cannot determine whether recovery is needed",
  comparisonUnavailableDescription:
    "The current file cannot be read, so {name} cannot be reliably compared or restored yet.",
  comparisonNeedsCurrentTitle: "Check the current file first",
  comparisonNeedsCurrentDescription:
    "This comparison uses the file as it was when {name} was saved. Open the current file before restoring.",
  comparisonSameTitle: "No recovery needed",
  comparisonSameDescription: "{name} matches the current version.",
  comparisonChangedTitle: "Review both versions",
  comparisonChangedDescription:
    "The original file changed after the draft was saved. Check both versions before restoring to the editor.",
  comparisonReadyDraftTitle: "Unsaved content is available",
  comparisonReadyPreviousTitle: "The previous saved version is available",
  comparisonReadyDraftDescription:
    "Restore this content to the editor if you need it. Save is required to write it to the file.",
  comparisonReadyPreviousDescription:
    "Restore the earlier version to the editor if needed. Save is required to write it to the file.",
  comparisonReading: "Reading the current file on disk…",
  comparisonReadError: "Cannot determine the current differences",
  comparisonReadFallback: "The current file is unavailable. Check that it exists and can be read.",
  comparisonRetry: "Read current version again",
  comparisonModifiedWarning:
    "The editor has unsaved edits. Recovery will replace those edits, but will not overwrite the file on disk automatically.",
  comparisonChangedWarning:
    "The original file changed after the draft was saved. The differences above use the current disk version.",
  comparisonOldBaseWarning:
    "The current file has not been read here. This compares only with the file as it was when {name} was saved.",
  comparisonNoDiff: "No visible differences between the current version and {name}; recovery is unnecessary.",
  comparisonTruncated: "This document is long, so only nearby differences are shown.",
  comparisonApproximate:
    "This document is long; this is a quick summary. Check the full text in the editor before restoring.",
  comparisonLoadingAction: "Reading…",
  comparisonUnavailableAction: "Recovery unavailable",
  comparisonRestoreAction: "Restore to editor",
  comparisonOpenAction: "Open document to confirm",
};

const messages: Record<Locale, Record<SafetyCopyKey, string>> = { "zh-CN": zh, "en-US": en };

export function safetyText(locale: Locale, key: SafetyCopyKey, values?: Record<string, string | number>): string {
  const message = messages[locale][key];
  if (!values) return message;
  return message.replace(/\{(\w+)\}/g, (placeholder, name: string) =>
    Object.hasOwn(values, name) ? String(values[name]) : placeholder,
  );
}

export function getSafetyCopyKeys(): readonly SafetyCopyKey[] {
  return Object.keys(zh) as SafetyCopyKey[];
}
