import { describe, expect, it } from "vitest";
import { resolveExternalChangeAction } from "./external-change";

describe("external document changes", () => {
  it("ignores changes unrelated to the active document", () => {
    expect(
      resolveExternalChangeAction({
        changedPaths: ["C:/Vault/other.md"],
        currentPath: "C:/Vault/today.md",
        modified: false,
        now: 100,
      }),
    ).toBe("ignore");
  });

  it("ignores the watcher event generated by the app's own save", () => {
    expect(
      resolveExternalChangeAction({
        changedPaths: ["C:/Vault/today.md"],
        currentPath: "C:/Vault/today.md",
        modified: false,
        selfWrittenUntil: 200,
        now: 199,
      }),
    ).toBe("ignore");
  });

  it("ignores watcher events while the app's write is still in flight", () => {
    expect(
      resolveExternalChangeAction({
        changedPaths: ["C:/Vault/today.md"],
        currentPath: "C:/Vault/today.md",
        modified: true,
        selfWriting: true,
        now: 200,
      }),
    ).toBe("ignore");
  });

  it("reloads an unmodified active document", () => {
    expect(
      resolveExternalChangeAction({
        changedPaths: ["C:/Vault/today.md"],
        currentPath: "C:/Vault/today.md",
        modified: false,
        now: 200,
      }),
    ).toBe("reload");
  });

  it("asks before replacing an active document with unsaved edits", () => {
    expect(
      resolveExternalChangeAction({
        changedPaths: ["C:/Vault"],
        currentPath: "C:/Vault/today.md",
        modified: true,
        now: 200,
      }),
    ).toBe("notify");
  });
});
